{{-- Component: Customer Agenda Timeline dengan Pengelompokan Status & Tipe Agenda --}}
{{-- Menampilkan jadwal meeting vendor dan agenda persiapan dengan visual yang membedakan --}}

@php
    // Group agenda berdasarkan status
    $scheduledAgendas = $agendas->filter(fn($a) => $a->status === 'scheduled')->sortBy('meeting_date');
    $completedAgendas = $agendas->filter(fn($a) => $a->status === 'completed')->sortByDesc('meeting_date');
    
    // Hitung total auto-generated vs manual
    $totalAutoGenerated = $agendas->where('is_auto_generated', true)->count();
    $totalManual = $agendas->where('is_auto_generated', false)->count();
@endphp

@if($agendas->isNotEmpty())
<div class="space-y-5">
    <div>
        <h3 class="font-bold text-base text-gray-900 mb-1 flex items-center gap-2">
            <svg class="w-6 h-6 text-pink-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/>
            </svg>
            Jadwal Acara & Agenda Persiapan
        </h3>
        <p class="text-xs text-gray-500">
            @if($totalAutoGenerated > 0)
                <span class="font-medium">{{ $totalAutoGenerated }} agenda otomatis</span> 
                @if($totalManual > 0) + @endif
            @endif
            @if($totalManual > 0)
                <span class="font-medium">{{ $totalManual }} agenda manual</span>
            @endif
        </p>
    </div>

    {{-- ===== AGENDA AKAN DATANG (SCHEDULED) ===== --}}
    @if($scheduledAgendas->isNotEmpty())
    <div class="space-y-3">
        <div class="flex items-center gap-2 pb-3 border-b border-gray-200">
            <svg class="w-5 h-5 text-blue-500" viewBox="0 0 24 24" fill="currentColor">
                <path d="M9 2a1 1 0 000 2h.01a1 1 0 000-2H9z"/>
                <path fill-rule="evenodd" d="M4 5a2 2 0 012-2 1 1 0 000 2h12a1 1 0 000-2 2 2 0 012 2v12a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm3.5.5a1 1 0 100 2 1 1 0 000-2zM7 8a1 1 0 100 2h10a1 1 0 100-2H7z" clip-rule="evenodd"/>
            </svg>
            <h4 class="font-semibold text-gray-900">Akan Datang</h4>
            <span class="ml-auto px-2 py-1 rounded-full text-xs font-semibold bg-blue-50 text-blue-700">
                {{ $scheduledAgendas->count() }} agenda
            </span>
        </div>

        <div class="space-y-3 pl-4">
            @foreach($scheduledAgendas as $agenda)
            @php
                $isToday = $agenda->isToday();
                $isOverdue = $agenda->isOverdue();
                $isUpcoming = $agenda->isUpcoming();
                $agendaIcon = $agenda->agenda_type_icon;
                $agendaTypeLabel = $agenda->agenda_type_label;
                $daysBeforeLabel = $agenda->days_before_event_label;
                
                // Determine urgency styling
                $urgencyClass = $isToday || $isOverdue 
                    ? 'border-l-4 border-red-400 bg-red-50' 
                    : ($isUpcoming ? 'border-l-4 border-yellow-300 bg-yellow-50' : 'border-l-4 border-blue-200 bg-blue-50');
            @endphp
            
            <div class="p-4 rounded-lg border border-gray-200 {{ $urgencyClass }} hover:shadow-md transition">
                <div class="flex items-start gap-3">
                    {{-- Icon Agenda Type --}}
                    <div class="text-2xl flex-shrink-0 mt-1">{{ $agendaIcon }}</div>
                    
                    <div class="flex-1 min-w-0">
                        <div class="flex items-start justify-between gap-2 mb-1">
                            <div>
                                <h5 class="font-semibold text-gray-900 text-sm leading-tight">{{ $agenda->title }}</h5>
                                @if($daysBeforeLabel)
                                <p class="text-xs text-gray-500 mt-1">📍 {{ $daysBeforeLabel }}</p>
                                @endif
                            </div>
                        </div>

                        {{-- Metadata: Tanggal, Waktu, Lokasi --}}
                        <div class="grid grid-cols-2 gap-2 mt-2 text-xs text-gray-600">
                            <div class="flex items-center gap-1">
                                <svg class="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/>
                                </svg>
                                <span>{{ $agenda->meeting_date->translatedFormat('d M Y') }}</span>
                            </div>
                            <div class="flex items-center gap-1">
                                <svg class="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/>
                                </svg>
                                <span>{{ substr($agenda->meeting_time, 0, 5) }} WIB</span>
                            </div>
                            <div class="col-span-2 flex items-center gap-1">
                                <svg class="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"/>
                                </svg>
                                <span class="truncate">{{ $agenda->location }}</span>
                            </div>
                        </div>

                        {{-- Agenda Type Badge --}}
                        <div class="mt-3 flex flex-wrap gap-2 items-center">
                            <span class="px-2.5 py-1 rounded text-xs font-semibold {{ $agenda->agenda_type_badge_class }}">
                                {{ $agendaTypeLabel }}
                            </span>
                            
                            @if($agenda->is_auto_generated)
                            <span class="px-2.5 py-1 rounded text-xs font-semibold bg-green-50 text-green-700 border border-green-200">
                                ✓ Auto-generated
                            </span>
                            @endif

                            @if($isToday)
                            <span class="px-2 py-1 rounded text-xs font-bold bg-red-100 text-red-700 border border-red-200 animate-pulse">
                                🔴 Hari Ini
                            </span>
                            @elseif($isUpcoming)
                            <span class="px-2 py-1 rounded text-xs font-semibold bg-yellow-100 text-yellow-700 border border-yellow-200">
                                ⏰ Segera Datang
                            </span>
                            @endif
                        </div>
                    </div>

                    {{-- Status Badge --}}
                    <div class="flex-shrink-0">
                        <span class="px-3 py-1.5 rounded-lg text-xs font-bold {{ $agenda->status_badge_class }} whitespace-nowrap">
                            {{ $agenda->status_label }}
                        </span>
                    </div>
                </div>

                {{-- Notes jika ada --}}
                @if($agenda->notes)
                <div class="mt-3 pt-3 border-t border-gray-200">
                    <p class="text-xs text-gray-600"><strong>Catatan:</strong> {{ $agenda->notes }}</p>
                </div>
                @endif
            </div>
            @endforeach
        </div>
    </div>
    @endif

    {{-- ===== AGENDA SELESAI (COMPLETED) ===== --}}
    @if($completedAgendas->isNotEmpty())
    <div class="space-y-3">
        <div class="flex items-center gap-2 pb-3 border-b border-gray-200">
            <svg class="w-5 h-5 text-green-500" viewBox="0 0 24 24" fill="currentColor">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"/>
            </svg>
            <h4 class="font-semibold text-gray-900">Selesai</h4>
            <span class="ml-auto px-2 py-1 rounded-full text-xs font-semibold bg-green-50 text-green-700">
                {{ $completedAgendas->count() }} agenda
            </span>
        </div>

        <div class="space-y-2 pl-4">
            @foreach($completedAgendas as $agenda)
            <div class="p-3 rounded-lg border border-gray-200 bg-green-50 opacity-75">
                <div class="flex items-start gap-3">
                    <div class="text-xl flex-shrink-0 mt-0.5">{{ $agenda->agenda_type_icon }}</div>
                    
                    <div class="flex-1 min-w-0">
                        <div class="flex items-start justify-between gap-2">
                            <div>
                                <h5 class="font-semibold text-gray-800 text-sm">{{ $agenda->title }}</h5>
                                <p class="text-xs text-gray-600 mt-1">
                                    {{ $agenda->meeting_date->translatedFormat('d M Y') }} · 
                                    {{ substr($agenda->meeting_time, 0, 5) }} · 
                                    {{ $agenda->location }}
                                </p>
                            </div>
                        </div>
                    </div>

                    <span class="px-2.5 py-1 rounded text-xs font-bold {{ $agenda->status_badge_class }} whitespace-nowrap flex-shrink-0">
                        {{ $agenda->status_label }}
                    </span>
                </div>
            </div>
            @endforeach
        </div>
    </div>
    @endif

    <p class="text-[10px] text-gray-400 pt-2 border-t border-gray-100">Meeting vendor & persiapan mandiri diurutkan dari tanggal terdekat.</p>
</div>
@endif
