<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class VendorMeeting extends Model
{
    use HasFactory;

    protected $table = 'vendor_meetings';

    protected $fillable = [
        'booking_id',
        'vendor_id',
        'korlap_id',
        'title',
        'meeting_date',
        'meeting_time',
        'location',
        'status',
        'notes',
        'agenda_type',
        'is_auto_generated',
        'days_before_event',
    ];

    protected function casts(): array
    {
        return [
            'meeting_date' => 'date',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
            'is_auto_generated' => 'boolean',
        ];
    }

    // ========================
    // RELATIONSHIPS
    // ========================

    /**
     * Meeting ini terkait dengan satu pesanan/booking.
     */
    public function booking()
    {
        return $this->belongsTo(Pesanan::class, 'booking_id');
    }

    public function vendor()
    {
        return $this->belongsTo(Vendor::class, 'vendor_id');
    }

    /**
     * Meeting ini ditangani oleh satu Korlap (Tim Lapangan).
     */
    public function korlap()
    {
        return $this->belongsTo(User::class, 'korlap_id');
    }

    // ========================
    // SCOPES
    // ========================

    /**
     * Scope untuk filter meeting yang belum selesai (scheduled/ongoing).
     * Berguna untuk menampilkan agenda penting di dashboard Korlap.
     */
    public function scopeUpcoming($query)
    {
        return $query->whereIn('status', ['scheduled', 'ongoing'])
                     ->orderBy('meeting_date', 'asc')
                     ->orderBy('meeting_time', 'asc');
    }

    /**
     * Scope untuk filter meeting berdasarkan Korlap ID.
     */
    public function scopeForKorlap($query, $korlapId)
    {
        return $query->where('korlap_id', $korlapId);
    }

    /**
     * Scope untuk filter meeting berdasarkan booking ID.
     */
    public function scopeForBooking($query, $bookingId)
    {
        return $query->where('booking_id', $bookingId);
    }

    /**
     * Scope untuk filter meeting yang sudah selesai.
     */
    public function scopeCompleted($query)
    {
        return $query->where('status', 'completed');
    }

    /**
     * Scope untuk filter meeting yang akan datang (scheduled).
     */
    public function scopeScheduled($query)
    {
        return $query->where('status', 'scheduled');
    }

    /**
     * Scope untuk filter agenda otomatis yang di-generate saat booking dp_paid.
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }

    /**
     * Scope untuk filter agenda manual (dibuat oleh admin/korlap).
     */
    public function scopeManual($query)
    {
        return $query->where('is_auto_generated', false);
    }

    /**
     * Scope untuk filter berdasarkan agenda type.
     */
    public function scopeByAgendaType($query, $type)
    {
        return $query->where('agenda_type', $type);
    }

    /**
     * Scope untuk filter agenda persiapan mandiri (self_preparation).
     */
    public function scopeSelfPreparation($query)
    {
        return $query->where('agenda_type', 'self_preparation');
    }

    /**
     * Scope untuk filter agenda technical meeting.
     */
    public function scopeTechnicalMeeting($query)
    {
        return $query->where('agenda_type', 'technical_meeting');
    }

    // ========================
    // ACCESSORS & MUTATORS
    // ========================

    /**
     * Label status meeting untuk UI Korlap: Segera, Pending, Selesai.
     */
    public function getDisplayStatusLabelAttribute(): string
    {
        if ($this->status === 'completed') {
            return 'Selesai';
        }

        if ($this->status === 'ongoing') {
            return 'Segera';
        }

        if ($this->isOverdue() || $this->isToday()) {
            return 'Segera';
        }

        if ($this->isUpcoming()) {
            return 'Segera';
        }

        return 'Pending';
    }

    public function getDisplayStatusBadgeClassAttribute(): string
    {
        return match ($this->display_status_label) {
            'Selesai' => 'bg-green-100 text-green-800 border border-green-300',
            'Segera' => 'bg-amber-100 text-amber-900 border border-amber-300',
            default => 'bg-slate-100 text-slate-700 border border-slate-300',
        };
    }

    public function isBookingFullyPaid(): bool
    {
        $booking = $this->booking;

        return $booking
            && ($booking->status_pembayaran === 'fully_paid' || $booking->isPembayaranLunas());
    }

    /**
     * Accessor: format status meeting dengan label Bahasa Indonesia.
     */
    public function getStatusLabelAttribute(): string
    {
        return match($this->status) {
            'scheduled' => 'Terjadwal',
            'ongoing' => 'Berlangsung',
            'completed' => 'Selesai',
            default => 'Unknown',
        };
    }

    /**
     * Accessor: format status dengan badge Tailwind CSS.
     */
    public function getStatusBadgeClassAttribute(): string
    {
        return match($this->status) {
            'scheduled' => 'bg-blue-50 text-blue-700 border border-blue-200',
            'ongoing' => 'bg-yellow-50 text-yellow-700 border border-yellow-200',
            'completed' => 'bg-green-50 text-green-700 border border-green-200',
            default => 'bg-gray-100 text-gray-700',
        };
    }

    /**
     * Accessor: format datetime meeting untuk tampilan di UI.
     */
    public function getFormattedDateTimeAttribute(): string
    {
        $date = $this->meeting_date->translatedFormat('d F Y');
        $time = $this->meeting_time;
        return "{$date} pukul {$time}";
    }

    /**
     * Accessor: status dan location dalam satu baris untuk preview.
     */
    public function getSummaryAttribute(): string
    {
        return "{$this->title} - {$this->status_label} ({$this->location})";
    }

    /**
     * Helper: cek apakah meeting sudah lewat (overdue).
     */
    public function isOverdue(): bool
    {
        return $this->meeting_date->isPast() && $this->status !== 'completed';
    }

    /**
     * Helper: cek apakah meeting hari ini.
     */
    public function isToday(): bool
    {
        return $this->meeting_date->isToday();
    }

    /**
     * Helper: cek apakah meeting segera datang (dalam 3 hari).
     */
    public function isUpcoming(): bool
    {
        return $this->meeting_date->isFuture() 
            && $this->meeting_date->diffInDays(now()) <= 3;
    }

    /**
     * Accessor: format agenda type dengan label Bahasa Indonesia.
     */
    public function getAgendaTypeLabelAttribute(): string
    {
        return match($this->agenda_type) {
            'technical_meeting' => 'Meeting Vendor',
            'self_preparation' => 'Persiapan Mandiri',
            default => 'Unknown',
        };
    }

    /**
     * Accessor: icon Tailwind untuk agenda type.
     * Berguna untuk menampilkan ikon visual di UI.
     */
    public function getAgendaTypeIconAttribute(): string
    {
        return match($this->agenda_type) {
            'technical_meeting' => '🎤', // Microphone untuk meeting
            'self_preparation' => '📝',  // Clipboard untuk preparation
            default => '📋',
        };
    }

    /**
     * Accessor: badge class Tailwind untuk agenda type.
     */
    public function getAgendaTypeBadgeClassAttribute(): string
    {
        return match($this->agenda_type) {
            'technical_meeting' => 'bg-purple-50 text-purple-700 border border-purple-200',
            'self_preparation' => 'bg-amber-50 text-amber-700 border border-amber-200',
            default => 'bg-gray-100 text-gray-700',
        };
    }

    /**
     * Accessor: format hari sebelum event (H-X).
     */
    public function getDaysBeforeEventLabelAttribute(): string
    {
        if (!$this->days_before_event) {
            return '';
        }

        if ($this->days_before_event === 0) {
            return 'H-0 (Hari H)';
        }

        return "H-{$this->days_before_event}";
    }

    /**
     * Accessor: check apakah ini agenda auto-generated.
     */
    public function getIsAutoGeneratedLabelAttribute(): string
    {
        return $this->is_auto_generated ? 'Auto-generated' : 'Manual';
    }
}
